// Starter presets. They set direction only: no user goals, branding, or
// references are invented, so context fields stay for the user to fill in.

import { createDefaultConfig } from "./config";
import { ESSENTIAL_A11Y } from "./options";
import type { Config, OptionEdit, Preset } from "./types";

interface PresetSeed {
  id: string;
  name: string;
  description: string;
  selected: string[];
  qualifiers?: Record<string, string>;
  pairs?: Record<string, string>; // pair id → scope ("" for unscoped)
  customInterfaceType?: string;
}

const SEEDS: PresetSeed[] = [
  {
    id: "precision-dashboard",
    name: "Precision dashboard",
    description:
      "Dense, aligned, and calm. For monitoring and operational data.",
    selected: [
      "interface.dashboard",
      "platform.desktop-web",
      "aesthetic.precision",
      "aesthetic.minimalist",
      "layout.grid",
      "layout.table-first",
      "density.compact",
      "density.balanced",
      "spacing.scale",
      "spacing.grouped",
      "type.heading-hierarchy",
      "type.dominant-primary",
      "type.subdued-meta",
      "type.restrained-scale",
      "type.mono-data",
      "theme.both",
      "palette.neutral",
      "palette.restrained-accent",
      "palette.semantic",
      "surface.tonal",
      "surface.outlined",
      "shape.modest",
      "ux.progressive",
      "ux.system-status",
      "ux.preserve-view",
      "ux.explicit-labels",
      "state.default",
      "state.hover",
      "state.focus",
      "state.selected",
      "state.loading",
      "state.empty",
      "state.error",
      "responsive.adapt-nav",
      "responsive.table-overflow",
      "responsive.no-hover-only",
    ],
    qualifiers: { "density.compact": "in tables and lists" },
    pairs: { focal: "", clutter: "", cards: "", glow: "" },
  },
  {
    id: "editorial-website",
    name: "Editorial website",
    description: "Typographic, spacious, and composed. For content-led sites.",
    selected: [
      "interface.marketing",
      "platform.responsive-web",
      "aesthetic.editorial",
      "aesthetic.premium",
      "layout.asymmetric",
      "layout.single-column",
      "density.spacious",
      "spacing.rhythm",
      "spacing.gutters",
      "type.heading-hierarchy",
      "type.contrast-headings",
      "type.readable-body",
      "type.expressive-display",
      "theme.light",
      "palette.neutral",
      "palette.restrained-accent",
      "surface.flat",
      "shape.angular",
      "ux.task-nav",
      "ux.explicit-labels",
      "motion.minimal",
      "state.default",
      "state.hover",
      "state.focus",
      "responsive.adapt-nav",
      "responsive.prioritize-mobile",
      "responsive.no-hover-only",
    ],
    qualifiers: {
      "layout.single-column": "for long-form articles",
      "type.expressive-display": "for page and section headlines only",
    },
    pairs: { "repeated-sections": "", clutter: "", gradients: "", cards: "" },
  },
  {
    id: "minimal-saas",
    name: "Minimal SaaS workspace",
    description: "Quiet, task-focused app chrome with thorough error handling.",
    customInterfaceType: "SaaS workspace application",
    selected: [
      "interface.custom",
      "platform.responsive-web",
      "aesthetic.minimalist",
      "aesthetic.utilitarian",
      "layout.sidebar",
      "layout.master-detail",
      "density.balanced",
      "spacing.scale",
      "spacing.grouped",
      "type.heading-hierarchy",
      "type.dominant-primary",
      "type.subdued-meta",
      "type.restrained-scale",
      "type.readable-body",
      "theme.system",
      "palette.neutral",
      "palette.restrained-accent",
      "palette.semantic",
      "surface.tonal",
      "surface.elevation",
      "shape.modest",
      "ux.task-nav",
      "ux.discoverable-primary",
      "ux.progressive",
      "ux.fewer-choices",
      "ux.inline-validation",
      "ux.destructive-confirm",
      "ux.preserve-input",
      "ux.actionable-errors",
      "ux.explicit-labels",
      "ux.microinteractions",
      "motion.minimal",
      "state.default",
      "state.hover",
      "state.focus",
      "state.selected",
      "state.disabled",
      "state.loading",
      "state.empty",
      "state.success",
      "state.error",
      "responsive.adapt-nav",
      "responsive.no-hover-only",
      "responsive.critical-actions",
    ],
    qualifiers: { "surface.elevation": "for menus, popovers, and dialogs" },
    pairs: { focal: "", clutter: "", "icon-only": "", animation: "" },
  },
  {
    id: "playful-onboarding",
    name: "Playful onboarding",
    description:
      "Friendly, step-by-step setup with personality and clear progress.",
    selected: [
      "interface.onboarding",
      "platform.responsive-web",
      "aesthetic.playful",
      "aesthetic.warm",
      "layout.single-column",
      "density.spacious",
      "spacing.grouped",
      "type.dominant-primary",
      "type.readable-body",
      "type.expressive-display",
      "theme.light",
      "palette.semantic",
      "palette.high-contrast-accent",
      "surface.tonal",
      "shape.strong",
      "shape.pill",
      "ux.progressive",
      "ux.fewer-choices",
      "ux.inline-validation",
      "ux.preserve-input",
      "ux.actionable-errors",
      "ux.explicit-labels",
      "ux.microinteractions",
      "motion.expressive",
      "state.default",
      "state.focus",
      "state.disabled",
      "state.loading",
      "state.success",
      "state.error",
      "responsive.prioritize-mobile",
      "responsive.critical-actions",
    ],
    qualifiers: {
      "type.expressive-display": "for step headlines",
      "motion.expressive": "for step transitions and the completion moment",
    },
    pairs: { focal: "", cramped: "", "icon-only": "" },
  },
  {
    id: "mobile-commerce",
    name: "Mobile-first commerce",
    description:
      "Thumb-friendly browsing and checkout with resilient error handling.",
    selected: [
      "interface.ecommerce",
      "platform.mobile-web",
      "aesthetic.premium",
      "aesthetic.minimalist",
      "layout.grid",
      "layout.single-column",
      "density.balanced",
      "spacing.scale",
      "spacing.gutters",
      "type.dominant-primary",
      "type.subdued-meta",
      "type.readable-body",
      "theme.light",
      "palette.neutral",
      "palette.restrained-accent",
      "palette.semantic",
      "surface.flat",
      "shape.modest",
      "shape.pill",
      "ux.discoverable-primary",
      "ux.system-status",
      "ux.inline-validation",
      "ux.preserve-input",
      "ux.actionable-errors",
      "ux.retry",
      "ux.preserve-view",
      "ux.explicit-labels",
      "state.default",
      "state.focus",
      "state.selected",
      "state.disabled",
      "state.loading",
      "state.empty",
      "state.success",
      "state.error",
      "responsive.adapt-nav",
      "responsive.prioritize-mobile",
      "responsive.no-hover-only",
      "responsive.critical-actions",
    ],
    qualifiers: {
      "layout.grid": "for product listings",
      "layout.single-column": "for product detail and checkout",
    },
    pairs: { "icon-only": "", clutter: "", gradients: "", cramped: "" },
  },
  {
    id: "dark-system",
    name: "Dark system interface",
    description: "Compact, engineered dark UI for technical operators.",
    selected: [
      "interface.admin",
      "platform.desktop-web",
      "aesthetic.precision",
      "aesthetic.industrial",
      "aesthetic.futuristic",
      "layout.sidebar",
      "layout.split-pane",
      "layout.table-first",
      "density.compact",
      "spacing.scale",
      "spacing.grouped",
      "type.contrast-headings",
      "type.subdued-meta",
      "type.restrained-scale",
      "type.mono-data",
      "theme.dark",
      "palette.neutral",
      "palette.semantic",
      "palette.high-contrast-accent",
      "surface.tonal",
      "surface.outlined",
      "shape.angular",
      "ux.system-status",
      "ux.destructive-confirm",
      "ux.actionable-errors",
      "ux.retry",
      "ux.preserve-view",
      "ux.explicit-labels",
      "motion.minimal",
      "state.default",
      "state.hover",
      "state.focus",
      "state.selected",
      "state.disabled",
      "state.loading",
      "state.empty",
      "state.success",
      "state.error",
      "responsive.table-overflow",
      "responsive.no-hover-only",
    ],
    pairs: {
      glow: "",
      gradients: "",
      contrast: "",
      clutter: "",
      whitespace: "",
    },
  },
];

function buildConfig(seed: PresetSeed): Config {
  const base = createDefaultConfig();
  const edits: Record<string, OptionEdit> = {};
  for (const [id, qualifier] of Object.entries(seed.qualifiers ?? {})) {
    edits[id] = { qualifier };
  }
  return {
    ...base,
    context: {
      ...base.context,
      customInterfaceType: seed.customInterfaceType ?? "",
    },
    selected: [...seed.selected, ...ESSENTIAL_A11Y],
    edits,
    avoidPairs: base.avoidPairs.map((p) =>
      seed.pairs && p.id in seed.pairs
        ? { ...p, enabled: true, scope: seed.pairs[p.id] }
        : p,
    ),
  };
}

export const BUILT_IN_PRESETS: Preset[] = SEEDS.map((s) => ({
  id: s.id,
  name: s.name,
  description: s.description,
  builtIn: true,
  config: buildConfig(s),
}));

/**
 * Produce an independent, editable copy of a preset's configuration. The
 * user's output-length preference is kept; the editor returns to brief mode.
 */
export function applyPreset(preset: Preset, current?: Config): Config {
  const copy = structuredClone(preset.config);
  return {
    ...copy,
    mode: "brief",
    outputLength: current?.outputLength ?? copy.outputLength,
  };
}
